name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy static assets to each platform
      run: |
        python scripts/copy_static_to_platforms.py

    - name: Build all platform docs
      run: |
        for dir in platform/*/*; do
          if [ -f "$dir/conf.py" ]; then
            echo "Building $dir"
            outdir="docs_build/${dir#platform/}"
            sphinx-build -b html -c . "$dir" "$outdir"
          fi
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_build
        publish_branch: gh-pages
