name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # 主分支名字，根据你仓库调整

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build top-level homepage docs
        run: |
          # 构建根目录（顶层首页），输出到 docs_build 根目录
          sphinx-build -b html . docs_build

      - name: Build all platform Sphinx docs
        run: |
          for dir in platform/*/*; do
            echo "Building $dir"
            sphinx-build -b html "$dir" "docs_build/${dir#platform/}"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
          publish_branch: gh-pages
          force_orphan: true
