name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    # 这里不生成首页index.rst，首页用你自己维护的

    - name: Build platform docs
      run: |
        for dir in platform/*/*; do
          if [ -f "$dir/conf.py" ]; then
            echo "Building $dir"
            outdir="docs_build/${dir#platform/}"
            sphinx-build -b html -c "$dir" "$dir" "$outdir"
          fi
        done

    # 不构建首页，只要确认首页静态文件放入docs_build根目录下
    - name: Copy manually maintained root index.html and assets
      run: |
        cp index.html docs_build/
        # 如果首页有静态文件夹，也复制过去，比如 _static
        cp -r _static docs_build/ || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_build
        publish_branch: gh-pages
