name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build top-level homepage
        run: |
          sphinx-build -b html . docs_build_homepage

      - name: Build all platform docs
        run: |
          for dir in platform/*/*; do
            echo "Building $dir"
            outdir="docs_build/${dir#platform/}"
            sphinx-build -b html "$dir" "$outdir"
          done

      - name: Merge homepage and platform docs
        run: |
          mkdir -p docs_build
          cp -r docs_build_homepage/* docs_build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
          publish_branch: gh-pages
          force_orphan: true
